[package]
name = "wat-gen"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "wat-gen"
path = "src/wat_gen_main.rs"

[dependencies]
wat = "1.235"

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
path = "../../framework/meta-lib"
